spring:
  profiles:
    active: h2, dbInitialization, csv

  h2:
    datasource:
      jdbcUrl: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  postgres:
    datasource:
      jdbcUrl: jdbc:postgresql://localhost:5432/medical_guide
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      hikari:
        idle-timeout: 10000
        minimum-idle: 1
        maximum-pool-size: 20
        pool-name: vtbClinicsPool
        auto-commit: false
  mysql:
    datasource:
      jdbcUrl: jdbc:mysql://localhost:3306/dms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 12345

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
